services:
  frontend:
    image: kevin950805/digital-photo-frame-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "4123:80"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    image: kevin950805/digital-photo-frame-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
      - UPLOAD_PATH=/app/uploads
    volumes:
      - ./database:/app/data
      - ./uploads:/app/uploads

networks:
  default:
    name: photo-frame-network